spring.application.name=event-api

# SPRING DOC
springdoc.swagger-ui.path=/api-docs.html
springdoc.api-docs.path=/api-docs
springdoc.packagesToScan=com.br.capoeira.eventos.evento_api.controller

# Rabbit Mq
spring.rabbitmq.host=localhost
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq
spring.rabbitmq.port=5672

rabbitmq.exchange.name=eventos.v1.novo-event

# Endpoints Banco-Api
banco.api.base.uri=http://localhost:8181/api/v1/event/base/dados/
banco.api.get.id.uri=?id=
banco.api.get.all.uri=all/

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB